### PR TITLE
propose an approach to GCS bucket management

### PR DESCRIPTION
**Pull request by wenzowski**
Hoping to get a feedback on the [proposed REST API](https://github.com/bcgov/cas-shelf/blob/9aa570976cecad1113a03c54454e2cab586575a3/docs/rest-api.md) first, then build out from this exploratory code.

### CODE REVIEW

**Comment by sheaphillips** [comment]
A few thoughts/comments - mostly notes for discussion on a call, which hopefully we can arrange for tomorrow:

- we should have TF Cloud as part of our stack pretty soon, so that could change and hopefullly simplify things here
- for the approach being proposed here, I'd suggest something more UNIX tool-like, rather than baking in multiple things into one tool (e.g. separating GCP infra provisioning and OpenShift integration into separate processes)
- I'm open to being convinced, but at this point I'm not positive an API is necessary/the right thing?  given availability of TF cloud, that removes at least part of the need, I think?  Maybe starting with cli-oriented tools that can be easily integrated into pipelines could work.
- I like the idea of coming up with an abstract representation of provisioning requests that could work across resources as well as providers.
- I'd like to understand the lifecycle/flow that you're imagining for when resources are provisioned, how they are configured/discovered etc.

**Comment by wenzowski** [comment]
Notes from yesterday:

- A provisioning API deployed to an OpenShift cluster has been ruled out
- TF Cloud will be used to store all provisioning state and to run the terraform provisioner
- TF Cloud will be configured with one workspace per tenant team
- TF Cloud will be configured in direct uploads mode for each workspace
- TF Cloud will initially be constrained by the features of the [free version](https://www.hashicorp.com/products/terraform/pricing/) during the pilot
- TF Cloud will use a [published module](https://www.terraform.io/docs/modules/publish.html) to encapsulate provisioning requests

Outstanding questions:

- Will it be possible to have workspaces configured in VCS repository mode instead?
- With only 5 user accounts available, will all workspaces be centrally managed?
- Can we remove multi-cloud abstractions from scope and build assuming future [module composition](https://www.terraform.io/docs/modules/composition.html#multi-cloud-abstractions)?
- Can we constrain the module dependency and testing lifecycle by applying a [trunk-pattern monorepo](https://trunkbaseddevelopment.com/monorepos/) to in-house TF modules?
- Can install an authorized service account on TF Cloud so we can inject authorized bucket-accesss keypairs and provisioned bucket config into openshift namespaces? Automatic injection enables key rotation during redeploy.

@junminahn have I missed anything?

**Comment by sheaphillips** [comment]
> Notes from yesterday:
> 
> * A provisioning API deployed to an OpenShift cluster has been ruled out

For clarity this is based on the availability of TF Cloud as a state backend.  

> * TF Cloud will be used to store all provisioning state and to run the terraform provisioner
> * TF Cloud will be configured with one workspace per tenant team

This is our initial thought, but further experimentation may lead us to another model (e.g. workspace per environment).

> * TF Cloud will be configured in direct uploads mode for each workspace

Not 100% sure if this is accurate.

> * TF Cloud will initially be constrained by the features of the [free version](https://www.hashicorp.com/products/terraform/pricing/) during the pilot

We intend to purchase seats of the paid offering.

> * TF Cloud will use a [published module](https://www.terraform.io/docs/modules/publish.html) to encapsulate provisioning requests

This is the initial thought, details will emerge as we experiment.
> 
> Outstanding questions:
> 
> * Will it be possible to have workspaces configured in VCS repository mode instead?

vs. direct upload mode?  likely, will need to confirm.

> * With only 5 user accounts available, will all workspaces be centrally managed?

Yes, that is the current thinking.  Interactions may be  just via TF Cloud Team API key. This is to be determined based on experimentation.

> * Can we remove multi-cloud abstractions from scope and build assuming future [module composition](https://www.terraform.io/docs/modules/composition.html#multi-cloud-abstractions)?

This can evolve.

> * Can we constrain the module dependency and testing lifecycle by applying a [trunk-pattern monorepo](https://trunkbaseddevelopment.com/monorepos/) to in-house TF modules?

Further discussion required on how TF modules are created, managed, etc.

> * Can install an authorized service account on TF Cloud so we can inject authorized bucket-accesss keypairs and provisioned bucket config into openshift namespaces? Automatic injection enables key rotation during redeploy.

I might be missing something, but I imagined that the provisioning interaction with TF would provide  keypairs, etc.  as outputs which could then be injected/configured into OpenShift.

> 
> @junminahn have I missed anything?

For now, I would not get blocked on any of the items above.  We are working towards GCP set up and getting you access to buckets.  The work around automation/CD integration (above) can follow.

**Comment by junminahn** [comment]
A couple more questions on my side:
- will it be a separate GCP project for each TFC workspace ?
- if yes, will the process to create a new project be automated or just a manual process just as creating a new OCP namespace for a new user(team) ?

**Comment by wenzowski** [comment]
@sheaphillips thank you for your thoughtful response

> For now, I would not get blocked on any of the items above. We are working towards GCP set up and getting you access to buckets. The work around automation/CD integration (above) can follow.

I really appreciate the confirmation that we're not blocked and GCP set-up is moving forward regardless. I do, however, want to note that we have a small window during which we have capacity to contribute our effort to CD integrations and ensure we're using the little time we have as effectively as possible. 

/cc @Maralsotoudehnia

**Comment by sheaphillips** [comment]
> @sheaphillips thank you for your thoughtful response
> 
> > For now, I would not get blocked on any of the items above. We are working towards GCP set up and getting you access to buckets. The work around automation/CD integration (above) can follow.
> 
> I really appreciate the confirmation that we're not blocked and GCP set-up is moving forward regardless. I do, however, want to note that we have a small window during which we have capacity to contribute our effort to CD integrations and ensure we're using the little time we have as effectively as possible.

Understood and appreciated.

> 
> /cc @Maralsotoudehnia

**Comment by Maralsotoudehnia** [comment]
> > @sheaphillips thank you for your thoughtful response
> > > For now, I would not get blocked on any of the items above. We are working towards GCP set up and getting you access to buckets. The work around automation/CD integration (above) can follow.
> > 
> > 
> > I really appreciate the confirmation that we're not blocked and GCP set-up is moving forward regardless. I do, however, want to note that we have a small window during which we have capacity to contribute our effort to CD integrations and ensure we're using the little time we have as effectively as possible.
> 
> Understood and appreciated.
> 
> > /cc @Maralsotoudehnia

@sheaphillips Grateful for all the hard work being done and at lightning speed. Reiterating @wenzowski in that we have a tiny window to get this all going. Thanks, again, all.

**Pull request closed without merging**
